name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Create env file
        run: |
          touch .env
          echo PUBLIC_URL="/react-pomodoro" >> .env
          echo REACT_APP_API_URL="https://ycjoyce-react-pomodoro.herokuapp.com" >> .env
          cat .env
      - name: Build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: build
